# Generated by Django 5.1.1 on 2024-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('class_mode', models.CharField(max_length=100)),
                ('class_hour', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.JSONField()),
                ('animation', models.CharField(max_length=50)),
            ],
        ),
    ]
