# Generated by Django 5.1.1 on 2024-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('animation', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
    ]
