# Generated by Django 5.1.1 on 2024-10-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
