# Generated by Django 5.1.1 on 2024-10-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rename_image_service_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('animation', models.CharField(max_length=50)),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
