# Generated by Django 5.1.1 on 2024-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_activeproject_product_image_product_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
