# Generated by Django 5.1.1 on 2024-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_product_title_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
