# Generated by Django 5.1.1 on 2024-10-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_remove_jobapplication_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_on',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
