# Generated by Django 5.1.1 on 2024-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='authorImage',
            field=models.ImageField(default='author_images/default_author.png', upload_to='author_images/'),
        ),
    ]
