# Generated by Django 5.1.1 on 2024-10-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_alter_blogpost_authorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='index_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
