# Generated by Django 5.1.1 on 2024-10-21 06:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_blogimage_index_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
