# Generated by Django 5.1.1 on 2024-10-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_alter_blogimage_content_alter_blogimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('blog_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='src.blogpost')),
            ],
        ),
    ]
