# Generated by Django 5.1.1 on 2024-10-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_blogpost_views_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
