# Generated by Django 5.1.1 on 2024-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0021_questionandanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="role",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
