# Generated by Django 5.1.1 on 2024-11-28 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0022_blogpost_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
