# Generated by Django 5.1.1 on 2024-12-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0023_jobapplication_created_at_jobapplication_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="benner/"),
                ),
            ],
        ),
    ]
