# Generated by Django 5.1.1 on 2024-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0024_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
    ]
